---
# File: site.yml - Hubot playbook for Vagrant based instance

- name: Hubot special variables
  hosts: hubot

- name: Hubot activate!
  hosts: hubot
  gather_facts: True
  sudo: True
  roles:
  - { role: brianshumate.hubot,
      hubot_adapter: slack,
      hubot_admin: vagrant,
      hubot_owner: "'Stephie Andretti <stephie@example.com>'",
      hubot_identity: griptape,
      hubot_description: Awesomeness 
    }
